<a href="https://colab.research.google.com/github/Stalkerino816/Projeto1Calculadora/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practice 2 - Decision Trees**
##Machine Learning – LECD, LEEC

###Informatics Engineering Department

**Goals: Use Decision trees to create models; prepare for first assignment**

#Ex1
1.1 Import libraries: 
- pandas, numpy
- sklearn.datasets <- load_iris
- sklearn.tree <- DecisionTreeClassifier
- sklearn.model_selection <- train_test_split
- sklearn.metrics <- accuracy_score
- sklearn.metrics <- confusion_matrix

1.2 Load IRIS dataset

In [ ]:
#To do: type your code here:
#1.1 imports
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

#1.2Loading the iris data
data = load_iris()
print('Classes to predict: ', data.target_names)

data

#Ex2: Extracting data attributes (X) and target/ class labels (y)

In [ ]:
#To do: type your code here:
#Extracting data atributes
X = data.data
print("Number of exampes in the data:", X.shape[0])
#Extracting target/ class atributes
Y = data.target

X[:4]

Number of exampes in the data: 150


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

#Ex3: Create train and test sets (train_test_split), 25% for testing

In [ ]:
#To do: type your code here:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 42)

#Ex4: Create a Decision Tree (DT) classifier based on entropy (DecisionTreeClassifier)

In [ ]:
#To do: type your code here:
clf = DecisionTreeClassifier(criterion = 'entropy')

#Ex5: Train the DT classifier

In [ ]:
#To do: type your code here:
clf.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy')

#Ex6: Predict labels on the test set.

In [ ]:
#To do: type your code here:
Y_pred = clf.predict(X_test)

Y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [ ]:
Y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

#Ex7: Evaluate results (accuracy on train and test set)

In [ ]:
#To do: type your code here (fill the ...):

print('Train data accuracy: ', accuracy_score(Y_train,clf.predict(X_train))) 
print('Test data accuracy: ', accuracy_score(Y_test,Y_pred))

#Typical Output:
#Train data accuracy:  1.0
#Test data accuracy:  0.9736842105263158

Train data accuracy:  1.0
Test data accuracy:  0.9736842105263158


#Ex8: Evaluate results (confusion matrix)

In [ ]:
#To do: type your code here (fill the ...):
cf_matrix = confusion_matrix(Y_test,Y_pred)
print(cf_matrix)

[[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]


#Ex9: Comment on results

In [ ]:
#This code generates a graphical confusion matrix
import seaborn as sns
import matplotlib.pyplot as plt
ax = sns.heatmap(cf_matrix, annot=True, cmap='Blues')
ax.set_title('Seaborn Confusion Matrix with labels\n\n');
ax.set_xlabel('\nPredicted Iris Category')
ax.set_ylabel('Actual Iris Category ');

## Ticket labels - List must be in alphabetical order
ax.xaxis.set_ticklabels(['Setosa','Versicolor', 'Virginia'])
ax.yaxis.set_ticklabels(['Setosa','Versicolor', 'Virginia'])

## Display the visualization of the Confusion Matrix.
plt.show()

Generate the confusion matrix using the code above and comment on the results:

#Ex10: Try different trees and comment

def __init__(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)

In [ ]:
#To do: type your code here 

Comment on results with different trees.
 #To do: write your comments here:

#Ex11 (extra): Generate a KNN Classifier and compare results.

In [ ]:
#To do: type your code here (fill the ...):

from sklearn.neighbors import KNeighborsClassifier as KNN

#create classifier
#knn = ...
#train the model
#knn.fit(...)
#y_pred = knn.predict(...)

#print('Train data accuracy: ', ...) 
#print('Test data accuracy: ', ...)
clf2 = KNN(3)

In [ ]:
clf2.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

#Ex12 (extra): Try different datasets

In [ ]:
from sklearn.datasets import load_breast_cancer 
breastCancer = load_breast_cancer()

X = breastCancer.data 
y = breastCancer.target

#To do: type your code